In [1]:
import torch
from hadamard_transform import hadamard_transform

In [2]:
import sys
import os

parent_dir = os.path.abspath(os.path.join(os.getcwd(), ".."))
if parent_dir not in sys.path:
    sys.path.append(parent_dir)

from pcdqv.standard_regularization import RandomizedHadamard

# Test 1

In [3]:
w = torch.arange(0, 16).reshape(4, 4).to(torch.float64)
w = w * 1.1
print(f"{w=}")

regularizer = RandomizedHadamard(
    p = w.shape[1],
)

w=tensor([[ 0.0000,  1.1000,  2.2000,  3.3000],
        [ 4.4000,  5.5000,  6.6000,  7.7000],
        [ 8.8000,  9.9000, 11.0000, 12.1000],
        [13.2000, 14.3000, 15.4000, 16.5000]], dtype=torch.float64)


In [4]:
w_forward = regularizer.forward(w)
w_forward

tensor([[-4.0089e-01, -1.2039e-01,  2.1822e-01, -0.0000e+00],
        [-1.4699e+00, -1.2039e-01,  2.1822e-01, -4.0171e-17],
        [-2.5390e+00, -1.2039e-01,  2.1822e-01, -8.0343e-17],
        [-3.6080e+00, -1.2039e-01,  2.1822e-01,  8.0343e-17]],
       dtype=torch.float64)

In [5]:
w_revesed = regularizer.reverse(w_forward)
w_revesed

tensor([[-2.2204e-16,  1.1000e+00,  2.2000e+00,  3.3000e+00],
        [ 4.4000e+00,  5.5000e+00,  6.6000e+00,  7.7000e+00],
        [ 8.8000e+00,  9.9000e+00,  1.1000e+01,  1.2100e+01],
        [ 1.3200e+01,  1.4300e+01,  1.5400e+01,  1.6500e+01]],
       dtype=torch.float64)

In [6]:
assert torch.allclose(
    w,
    regularizer.reverse(w_forward),
)

# Test 2

In [7]:
w = torch.arange(0, 20).reshape(4, 5).to(torch.float64)
w = w * 1.1
print(f"{w=}")


regularizer = RandomizedHadamard(
    p = w.shape[1],
)

w=tensor([[ 0.0000,  1.1000,  2.2000,  3.3000,  4.4000],
        [ 5.5000,  6.6000,  7.7000,  8.8000,  9.9000],
        [11.0000, 12.1000, 13.2000, 14.3000, 15.4000],
        [16.5000, 17.6000, 18.7000, 19.8000, 20.9000]], dtype=torch.float64)


In [8]:
w_forward = regularizer.forward(w)
w_forward

tensor([[-5.3452e-01,  9.8295e-02, -0.0000e+00, -1.6813e-01, -7.8206e-02,
         -5.5365e+07,  7.3820e+07,  3.6910e+07],
        [-1.8708e+00,  3.4403e-01, -2.2680e-01, -3.7830e-01, -6.6475e-01,
         -1.0150e+08,  1.1996e+08,  8.3047e+07],
        [-3.2071e+00,  5.8977e-01, -4.5361e-01, -5.8846e-01, -1.2513e+00,
         -1.4764e+08,  1.6609e+08,  1.2918e+08],
        [-4.5434e+00,  8.3550e-01, -6.8041e-01, -7.9863e-01, -1.8378e+00,
         -1.9378e+08,  2.1223e+08,  1.7532e+08]], dtype=torch.float64)

In [9]:
w_revesed = regularizer.reverse(w_forward)
w_revesed

tensor([[ 0.0000,  1.1000,  2.2000,  3.3000,  4.4000],
        [ 5.5000,  6.6000,  7.7000,  8.8000,  9.9000],
        [11.0000, 12.1000, 13.2000, 14.3000, 15.4000],
        [16.5000, 17.6000, 18.7000, 19.8000, 20.9000]], dtype=torch.float64)

In [10]:
assert torch.allclose(
    w,
    regularizer.reverse(w_forward),
)

# Test 3

In [11]:
w = torch.arange(0, 16).reshape(4, 4).to(torch.float32)
w = w * 1.1
print(f"{w=}")

regularizer = RandomizedHadamard(
    p = w.shape[1],
)

w=tensor([[ 0.0000,  1.1000,  2.2000,  3.3000],
        [ 4.4000,  5.5000,  6.6000,  7.7000],
        [ 8.8000,  9.9000, 11.0000, 12.1000],
        [13.2000, 14.3000, 15.4000, 16.5000]])


In [12]:
w_forward = regularizer.forward(w)
w_forward

tensor([[-4.0089e-01, -1.2039e-01,  2.1822e-01, -5.3917e-09],
        [-1.4699e+00, -1.2039e-01,  2.1822e-01, -0.0000e+00],
        [-2.5390e+00, -1.2039e-01,  2.1822e-01, -0.0000e+00],
        [-3.6080e+00, -1.2039e-01,  2.1822e-01, -0.0000e+00]])

In [13]:
w_revesed = regularizer.reverse(w_forward)
w_revesed

tensor([[-1.1921e-07,  1.1000e+00,  2.2000e+00,  3.3000e+00],
        [ 4.4000e+00,  5.5000e+00,  6.6000e+00,  7.7000e+00],
        [ 8.8000e+00,  9.9000e+00,  1.1000e+01,  1.2100e+01],
        [ 1.3200e+01,  1.4300e+01,  1.5400e+01,  1.6500e+01]])

In [16]:
assert torch.allclose(
    w,
    regularizer.reverse(w_forward),
    rtol=1e-05,
    atol=1e-05
)